// deliv: [same-day, next-thurs, when-ready]
// false means available, true means not available
export const catalogue = [
  {
    pid: 0,
    name: "Bag of Chips [Classic]",
    price: 5,
    tags: ["Food", "Vegan"],
    pic: "https://blog.counselfinancial.com/hubfs/EMAIL_Images/Association%20Endorsements/potato-chips-448737_640.jpg",
    desc: "You get a RANDOM bag of chips. Try your luck and see if you get the bag you want.",
    deliv: [true, false, false],
  },
  {
    pid: 1,
    name: "Can of Pepsi",
    price: 6,
    tags: ["Drink", "Vegan"],
    pic: "https://www.snackhistory.com/wp-content/uploads/2022/02/Pepsi-3.jpg",
    desc: "Sorry we don't have coke. Is Pepsi okay? Same-day pick up available. Sugar-free option available.",
    deliv: [false, false, false],
  },
  {
    pid: 2,
    name: "Oreos [Pack of 2]",
    price: 3,
    tags: ["Food", "Vegan"],
    pic: "https://static.onecms.io/wp-content/uploads/sites/19/2021/08/12/oreo-hero.jpg",
    desc: "Sometimes you just CRAVE an oreo. You don't need a lot; just one or two. Same-day pick up available.",
    deliv: [false, false, false],
  },
  {
    pid: 3,
    name: "Principal for a Day",
    price: 52,
    tags: ["Experience", "Vegan"],
    pic: "https://drive.google.com/uc?id=1X1k6ClQ7wW8N6OqqSyjXzpAFxqaIuk4E",
    desc: "Take Mr. Georgino's job for a day! Kinda. You will shadow Mr. Georgino and live a day in his shoes.",
    deliv: [true, true, false],
  },
  {
    pid: 4,
    name: "WINGSmate",
    price: 16,
    tags: ["Experience", "Vegan"],
    pic: "https://cdn-prod.medicalnewstoday.com/content/images/articles/326/326263/person-running-in-the-forest.jpg",
    desc: "Challenge one of your teachers to run the mile or trail with you. Click below for the list of all available teachers",
    deliv: [true, true, false],
    link: "https://docs.google.com/document/d/e/2PACX-1vSTMNcX8JzvZN5775rpYrTlGna3t1vuTlC0iKVBRsQQyJsuvNf6IvGWVGky9qjvEcsEAKDzu3sV1S0O/pub",
  },
  {
    pid: 5,
    name: "Pickleball",
    price: 32,
    tags: ["Merch", "Vegan"],
    pic: "https://cityofukiah.com/wp-content/uploads/2022/05/pickleball-3-1920x1054-1.jpg",
    desc: "Franklin X-40 Outdoor Pickleball, USAPA Approved. Neon-green. Is it supposed to look like a pickle?",
    deliv: [true, true, false],
  },
  {
    pid: 6,
    name: "Cup Noodles [Made]",
    price: 11,
    tags: ["Food", "Hot", "Vegan"],
    pic: "https://www.adweek.com/wp-content/uploads/files/cup-noodles-hed-2015.jpg",
    desc: "Smells good. Delivered right before lunch. Vegan options available with a slightly longer wait.",
    deliv: [true, false, false],
  },
];
