// deliv: [same-day, next-thurs, when-ready]
// false means available, true means not available
export const catalogue = [
  {
    pid: 24,
    name: "Teacher Appreciation Gram",
    price: 3,
    tags: ["Limited Time"],
    pic: "https://www.scetv.org/sites/default/files/blogs/ThankYouTeachers.png",
    desc: "Send a special hand-written note to thank your teacher! ASB will deliver you a blank template after you order, collect them outside D-9 during lunch, and deliver them on your behalf! Limited time: Order by Wednesday 05/03.",
    deliv: [true, false, false],
    sold: "hidden",
  },
  {
    pid: 21,
    name: "Cookie Decorating",
    price: 8,
    tags: ["Limited Time"],
    pic: "https://www.number-2-pencil.com/wp-content/uploads/2019/12/Cookie-Decorating-Party-3.jpg",
    desc: "No other food will be available at the dance (03/17) so don't miss this opportunity to decorate a cookie! You will receive a pass on the day of the dance. Yummmmm!",
    deliv: [true, false, false],
    sold: "hidden",
  },
  {
    pid: 22,
    name: "VIP Access Pass",
    price: 37,
    tags: ["Food", "Limited Time"],
    pic: "https://drive.google.com/uc?id=1mP73DE74i5TTxQCjFLw-_ksxR2uAhib2",
    desc: "Don't worry about waiting in line for ANYTHING at the dance (03/17)! Obstacle course, arcade games, karaoke, cookie decorating (separate purchase), and more!",
    deliv: [true, false, false],
    sold: "hidden",
  },
  {
    pid: 23,
    name: "Hawaiian Lei",
    price: 15,
    tags: ["Limited Time"],
    pic: "https://asset.bloomnation.com/c_pad,d_vendor:global:catalog:product:image.png,f_auto,fl_preserve_transparency,q_auto/v1675310684/vendor/694/catalog/product/2/0/20190930083719_file_5d92677f8df01_5d926787c7788.jpg",
    desc: "A Hawaiian Lei that you can wear to the dance, and more! The possibilities are limitless. At this price of 15 WINGS tickets, it's a steal!",
    deliv: [true, false, false],
    sold: "hidden",
  },
  {
    pid: 0,
    name: "Bag of Chips [Classic]",
    price: 5,
    tags: ["Food", "Vegan"],
    pic: "https://blog.counselfinancial.com/hubfs/EMAIL_Images/Association%20Endorsements/potato-chips-448737_640.jpg",
    desc: "You get a RANDOM bag of chips. Try your luck and see if you get the bag you want.",
    deliv: [true, false, false],
    sold: "out",
  },
  {
    pid: 1,
    name: "Can of Pepsi",
    price: 8,
    tags: ["Drink", "Vegan"],
    pic: "https://www.snackhistory.com/wp-content/uploads/2022/02/Pepsi-3.jpg",
    desc: "Sorry we don't have coke. Is Pepsi okay? Diet options available.",
    deliv: [true, false, false],
    options: ["Diet"],
    sold: "out",
  },
  {
    pid: 2,
    name: "Oreos [Pack of 2]",
    price: 5,
    tags: ["Food"],
    pic: "https://static.onecms.io/wp-content/uploads/sites/19/2021/08/12/oreo-hero.jpg",
    desc: "Sometimes you just CRAVE an oreo. You don't need a lot; just one or two.",
    deliv: [true, false, false],
    sold: "out",
  },
  {
    pid: 3,
    name: "Georgino for a Day",
    price: 52,
    tags: ["Experience"],
    pic: "https://drive.google.com/uc?id=1X1k6ClQ7wW8N6OqqSyjXzpAFxqaIuk4E",
    desc: "Be Principal for a day! Shadow Mr. Georgino as he shows you what his job really means. You'll take on the responsibility of JTMS.",
    deliv: [true, true, false],
    sold: "out",
  },
  {
    pid: 4,
    name: "Levensailor for a Day",
    price: 52,
    tags: ["Experience"],
    pic: "https://drive.google.com/uc?id=18fI0rsRjgptBcie6x2y_OU7p-qEpyTW8",
    desc: "Be Assistant Principal for a day! Live a day in her shoes, learn the ins and outs of her job, and help manage the school for a day. ",
    deliv: [true, true, false],
    sold: "out",
  },
  {
    pid: 5,
    name: "Pickleball",
    price: 32,
    tags: ["Merch"],
    pic: "https://cityofukiah.com/wp-content/uploads/2022/05/pickleball-3-1920x1054-1.jpg",
    desc: "Franklin X-40 Outdoor Pickleball, USAPA Approved. Neon-green. Is it supposed to look like a pickle?",
    deliv: [true, true, false],
  },
  {
    pid: 6,
    name: "Cup Noodles [Made]",
    price: 17,
    tags: ["Food", "Hot"],
    pic: "https://www.adweek.com/wp-content/uploads/files/cup-noodles-hed-2015.jpg",
    desc: "Smells good. Come grab it at the start of lunch. Vegan options NO LONGER available.",
    deliv: [true, false, false],
    options: ["Chicken Flavor", "Shrimp Flavor"],
    sold: "out",
  },
  {
    pid: 7,
    name: "WINGSmate",
    price: 16,
    tags: ["Experience"],
    pic: "https://cdn-prod.medicalnewstoday.com/content/images/articles/326/326263/person-running-in-the-forest.jpg",
    desc: "Challenge one of your teachers to run the mile or trail with you. Click below for the list of all available teachers",
    deliv: [true, true, false],
    link: "https://docs.google.com/document/d/e/2PACX-1vSTMNcX8JzvZN5775rpYrTlGna3t1vuTlC0iKVBRsQQyJsuvNf6IvGWVGky9qjvEcsEAKDzu3sV1S0O/pub",
  },
  {
    pid: 8,
    name: "Mac n Cheese [Made]",
    price: 19,
    tags: ["Food", "Vegetarian"],
    pic: "https://www.champagneandcoffeestains.com/wp-content/uploads/2021/02/bowl-of-kraft-macaroni-and-cheese.jpg",
    desc: "Warm and cheesy~ Upgrade your lunch with a a special lunch.",
    deliv: [true, false, false],
    sold: "out",
  },
  {
    pid: 9,
    name: "Fake Orange",
    price: 21,
    tags: ["Merch"],
    pic: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/S/aplus-media/sc/dacc10c3-706c-40cf-a948-a7de629274a1.__CR0,0,300,300_PT0_SX300_V1___.jpg",
    desc: "Life is like an orange - it's pretty amazing. Here's an orange that will never go bad.",
    deliv: [true, false, false],
    sold: "out",
  },
  {
    pid: 10,
    name: "Retro Vintage JTMS Pen",
    price: 19,
    tags: ["Merch", "Limited Edition"],
    pic: "https://drive.google.com/uc?id=117KlOSCk3kGAjkFFotUAJxy4Yuss04mL",
    desc: "Brought back for a limited time! Beautifully crafted, JTMS branded pens will bless you during a test.",
    deliv: [true, false, false],
  },
  {
    pid: 11,
    name: "1 v. 1 Basketball",
    price: 16,
    tags: ["Experience"],
    pic: "https://drive.google.com/uc?id=1OIJXsvgNa884UEXg87G25U5-mQSnO6_8",
    desc: "Win against a teacher at basketball for a special prize. Click below for available teachers.",
    deliv: [true, true, false],
    link: "https://docs.google.com/document/d/e/2PACX-1vSTMNcX8JzvZN5775rpYrTlGna3t1vuTlC0iKVBRsQQyJsuvNf6IvGWVGky9qjvEcsEAKDzu3sV1S0O/pub",
  },
  {
    pid: 12,
    name: "1 v. 1 Pickletball",
    price: 16,
    tags: ["Experience"],
    pic: "https://drive.google.com/uc?id=1dLoc4kY-OcHfyrZoNVUQwB7vWq4WWINl",
    desc: "Win against a staff member at pickleball to earn a special prize. Click below to see available members.",
    deliv: [true, true, false],
    link: "https://docs.google.com/document/d/e/2PACX-1vSTMNcX8JzvZN5775rpYrTlGna3t1vuTlC0iKVBRsQQyJsuvNf6IvGWVGky9qjvEcsEAKDzu3sV1S0O/pub",
  },
  {
    pid: 13,
    name: "Gatorade",
    price: 8,
    tags: ["Drink"],
    pic: "https://s3-prod.adage.com/s3fs-public/20220215_Gatorade_3x2.jpg",
    desc: "It's a hot day, and you just ran a mile. Time to cool down and replenish your electrolytes.",
    deliv: [true, false, false],
    options: ["Refrigerated"],
    sold: "out",
  },
  {
    pid: 14,
    name: "Vintage JTMS Shirt",
    price: 23,
    tags: ["Merch"],
    pic: "https://drive.google.com/uc?id=1iiRxMV2Oo2CsL-ReLejLMlTKvWyTSyqi",
    desc: "Limited edition, old school throwback JTMS Spirit gear. Limited sizes and designs available.",
    deliv: [true, false, false],
    options: ["Size S", "Size M", "Size L", "Size XL"],
  },
  {
    pid: 15,
    name: "Vintage JTMS Hoodie",
    price: 39,
    tags: ["Merch"],
    pic: "https://drive.google.com/uc?id=1rY3uD9Gl1oMs0K3TeegbiDSjYEBkTRrT",
    desc: "Limited edition, old school throwback JTMS Spirit gear. Limited sizes and designs available.",
    deliv: [true, false, false],
    options: ["Size S", "Size M"],
    sold: "out",
  },
  {
    pid: 16,
    name: "Can of Sprite",
    price: 8,
    tags: ["Drink", "Merch", "Vegan"],
    pic: "https://isitbadforyou.s3.amazonaws.com/uploads/article/pictures/223/big_is_sprite_bad_for_you_2.jpg",
    desc: "Do you want a coke but without caffeine? Here's a *Sprite. Much better than a 7-Up. Diet version available upon request.",
    deliv: [true, false, false],
    options: ["Sugar-free"],
    sold: "out",
  },
  {
    pid: 17,
    name: "Hello Panda Cookies",
    price: 5,
    tags: ["Food"],
    pic: "https://cdn.shopify.com/s/files/1/0972/7116/products/Meiji-Hello-Panda-Chocolate-Mini-Cookies-3-768x768_2048x.jpg?v=1652369963",
    desc: "Crunchy on the outside, soft and chocolatey on the inside. Sharing size, and bite-sized.",
    deliv: [true, false, false],
  },
  {
    pid: 18,
    name: "Tech Deck Fingerboard",
    price: 28,
    tags: ["Merch"],
    pic: "https://m.media-amazon.com/images/W/WEBP_402378-T1/images/I/81MZ6hG0psL._AC_SL1500_.jpg",
    desc: "Official Tech Decks; several designs available. Please don't play with them in class. We don't take responsibility if they get taken away lol.",
    deliv: [true, true, false],
    sold: "out",
  },
  {
    pid: 19,
    name: "$5 Gift Card",
    price: 48,
    tags: ["Merch", "Vegan"],
    pic: "https://hips.hearstapps.com/hmg-prod/images/walgreens-gift-cards-display-news-photo-614264964-1545846134.jpg?crop=1xw:0.7501xh;center,top&resize=1200:*",
    desc: "This one's self-explanatory. Target, Starbucks, 7Leaves, Lollicup, Chic-fil-a, Chipotle, First Class Pizza",
    deliv: [true, false, false],
  },
  {
    pid: 20,
    name: "Front of Lunchline Pass",
    price: 3,
    tags: ["Experience"],
    pic: "https://drive.google.com/uc?id=1cw0lZuRZE7GhcdcqjrqDUOxQvtF63MnC",
    desc: "Got a lunch club to run? Got a game to win? Got the urge to just skip the line? Well this pass is for you. Single-use, and non-transferable.",
    deliv: [true, false, false],
  },
];
